# Generated by Django 4.0.4 on 2022-04-12 21:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to=core.models.upload_to_fn)),
                ('f_json', models.JSONField()),
            ],
        ),
    ]
